# SUPPORT VECTOR MACHINE(SVM) REGRESSION

In [2]:
import pandas as pd
import numpy as np

In [6]:
path = r"https://drive.google.com/uc?export=download&id=1xxDtrZKfuWQfl-6KA9XEd_eatitNPnkB" 
df = pd.read_csv(path)
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [7]:
X = df.drop('price' ,axis =1)
y = df['price']
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X,y , test_size = 0.2 ,random_state = 51 )


print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)


Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

# SVM regression ml training

In [13]:
from sklearn.svm import SVR

In [14]:
svr_rbf = SVR()
svr_rbf.fit(X_train , y_train)
svr_rbf.score(X_test , y_test)

0.20638035840828173

In [15]:
#NOT VERY GOOD ACCURACY 

In [18]:
#NOW CHANGE KERNEL linear
svr_linear = SVR(kernel='linear')
svr_linear.fit(X_train , y_train)
svr_linear.score(X_test , y_test)

0.7962632908376728

In [19]:
#much better accuracy

In [20]:
#NOW CHANGE KERNEL poly
svr_poly = SVR(kernel='poly',degree =2)
svr_poly.fit(X_train , y_train)
svr_poly.score(X_test , y_test)

0.18266215211874637

In [ ]:
#KERNEL linear is  suitable
svr_linear = SVR(kernel='linear')
svr_linear.fit(X_train , y_train)
svr_linear.score(X_test , y_test)

In [21]:
X_test[0:,]

array([[ 0.71301986,  0.0112734 ,  0.30202307, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.58028511, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [ 1.86878568,  0.55008644,  0.62450413, ..., -0.05630391,
        -0.05630391, -0.05138463],
       ...,
       [-1.59851179,  0.55008644, -1.03304852, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -0.74630813, -0.38550655, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -2.0427027 ,  0.12917322, ..., -0.05630391,
        -0.05630391, -0.05138463]])

In [25]:
#NOW CHANGE KERNEL linear
svr_linear.predict([X_test[0]])

array([86.53635296])

In [28]:
#all houses predict 
y_pred = svr_linear.predict(X_test)
y_pred

array([ 86.53635296,  33.70328324, 122.48693302, ...,  26.23969196,
        64.52605283, 176.17199988])

In [29]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

# rmse error

In [30]:
from sklearn.metrics import mean_squared_error

In [31]:
MSE = mean_squared_error(y_test,y_pred)
MSE

4093.668844267616

In [32]:
RMSE = np.sqrt(MSE)
print("MSE " ,MSE)
print("RMSE" ,RMSE)


MSE  4093.668844267616
RMSE 63.98178525383311
